UPDATE LIMIT_MANAGEMENT_SERVICE.USER_MONTHLY_LIMIT
SET ID = 266,
    CREATED_BY = 'SYSTEM',
    CREATED_DATE = TIMESTAMP '2023-11-01 14:06:32.338000',
    MODIFIED_BY = NULL,
    MODIFIED_DATE = NULL,
    USER_PROFILE_ID = 665,
    USING_DEFAULT_LIMIT = 1,
    CURRENCY = 'USD',
    MAX_AMOUNT_PER_TRANSACTION = 25000,
    MAX_AMOUNT_MONTHLY = 10000,
    LAST_TRANSACTION_DATE = TIMESTAMP '2023-11-01 14:06:32.338000',
    CURRENT_TOTAL_AMOUNT_MONTHLY = 0,
    REMAINING_MONTHLY_TRANSACTIONS = 100,
    TRANSACTION_CATEGORY = 'TRANSACTION_VALAS_BELI',
    TRANSACTION_CODE = 'ALL',
    TRANSACTION_GROUP = 3,
    SEGMENT_CODE = 'REGULER'
WHERE USER_PROFILE_ID = '665' AND TRANSACTION_CATEGORY = 'TRANSACTION_VALAS_BELI';